name: Run Git Commands in Ubuntu Runner

on:
  push:
    branches:
      - main

jobs:
  git-commands:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      uses: actions/checkout@v2

    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git

    - name: Verify Git installation
      run: git --version

    - name: Run a Git command
      run: git config --list
